- description: null
  label: "News"
  name: "news"
  sort: 1
  listed: true
  hasRoute: true
  showAsTable: false
  parent: null
  fields:
    - name: "header_text"
      label: "Header Text"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
- description: null
  label: "Jump Nav"
  name: "jump_nav"
  sort: 1
  listed: true
  hasRoute: false
  showAsTable: false
  parent: "news_post"
  fields:
    - name: "link_text"
      label: "Link Text"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "href"
      label: "Href"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
- description: null
  label: "Related Posts"
  name: "related_posts"
  sort: 1
  listed: true
  hasRoute: false
  showAsTable: false
  parent: "news_post"
  fields:
    - name: "related_posts_header"
      label: "Featured Posts Header"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "related_posts"
      label: "Featured Posts"
      description: null
      datatype: "link"
      sort: 1
      required: true
      relationship: null
- description: null
  label: "News Post"
  name: "news_post"
  sort: 1
  listed: true
  hasRoute: true
  showAsTable: true
  parent: "news"
  fields:
    - name: "sub_text"
      label: "List Summary"
      description: null
      datatype: "textarea"
      sort: 1
      required: true
      relationship: null
    - name: "header_text"
      label: "Heading"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "sub_header"
      label: "Sub Heading"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "featured_image"
      label: "Featured Image"
      description: null
      datatype: "images"
      sort: 1
      required: null
      relationship: null
      settings:
        limit: 1
        list: false
    - name: "is_feature_clipped"
      label: "Clip Featured Image"
      description: null
      datatype: "yes_no"
      sort: 1
      required: true
      relationship: null
      settings:
        list: true
        options:
          0: "No"
          1: "Yes"
    - name: "featured_image_alt"
      label: "Featured Image Alt Text"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "featured_video"
      label: "Featured Video"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "schemamarkup"
      label: "Schema Markup"
      description: null
      datatype: "textarea"
      sort: 1
      required: true
      relationship: null
    - name: "jump_nav"
      label: "Jump Nav"
      description: null
      datatype: "one_to_many"
      sort: 1
      required: false
      relationship:
        name: "jump_nav"
        display: "link_text"
      settings:
        list: true
    - name: "show_related_posts"
      label: "Show Related Posts"
      description: null
      datatype: "yes_no"
      sort: 1
      required: true
      relationship: null
      settings:
        list: true
        options:
          0: "No"
          1: "Yes"
    - name: "related_posts"
      label: "Related Posts"
      description: null
      datatype: "one_to_many"
      sort: 1
      required: false
      relationship:
        name: "related_posts"
        display: "related_posts_header"
      settings:
        list: true
    - name: "body"
      label: "Body"
      description: null
      datatype: "wysiwyg_basic"
      sort: 1
      required: true
      relationship: null
